### ISSUE TITLE
好象又错误了，显示”接收数据失败(1)“

### ISSUE THREAD

**Issue by xgguest** [TkzcM/pandownload-login#12]
[好象又错误了，显示”接收数据失败(1)“

**Comment by TkzcM** [comment]
修改过hosts请去掉那一行

**Comment by aoliann** [comment]
> 修改过hosts请去掉那一行

大佬，还是显示登录失败...

**Comment by aoliann** [comment]
> 修改过hosts请去掉那一行

Addon error: Traceback (most recent call last):
  File "pdproxy.py", line 16, in response
IndexError: list index out of range

**Comment by TkzcM** [comment]
> > 修改过hosts请去掉那一行
> 
> Addon error: Traceback (most recent call last):
> File "pdproxy.py", line 16, in response
> IndexError: list index out of range

Cookies 登录请同时输入bduss和stoken
