### ISSUE TITLE
 File "pdproxy.py", line 16, in response IndexError: list index out of range

### ISSUE THREAD

**Issue by nk950357** [TkzcM/pandownload-login#15]
`https://i.imgur.com/HTEPx4a.png`
請問這要怎麼解決呢
剛剛從release下載

**Comment by TkzcM** [comment]
使用 cookies 登录请同时填写 bduss 和 stoken
否则无法登录

**Comment by nk950357** [comment]
> 使用 cookies 登录请同时填写 bduss 和 stoken
> 否则无法登录

是貼在bduss後面嗎?

**Comment by nk950357** [comment]
> 使用 cookies 登录请同时填写 bduss 和 stoken
> 否则无法登录

後來改用帳號密碼登入就可以了 感謝
膜拜大神!

**Comment by nk950357** [comment]
但現在問題是顯示錯誤2 獲取下載連結失敗

**Comment by TkzcM** [comment]
> 但現在問題是顯示錯誤2 獲取下載連結失敗

不解决下载问题
