### ISSUE TITLE
proxy闪退

### ISSUE THREAD

**Issue by Evinqian** [TkzcM/pandownload-login#2]
![Screenshot_2020-06-01-21-06-56-514_com miui video](https://user-images.githubusercontent.com/32667159/83412011-fc436880-a44b-11ea-94f5-12b31c1bc16b.jpg)
求解决方法
太快无法截屏，只好慢镜头拍摄，请见谅。

**Comment by TkzcM** [comment]
请试试新版
https://github.com/TkzcM/pandownload-login/releases/tag/v0.2

**Comment by stayrabbit** [comment]
可以用感謝作者

**Comment by Evinqian** [comment]
非常感谢qwq
