### ISSUE TITLE
大佬，pd登陆没问题了，但下载显示获取下载链接失败（2）

### ISSUE THREAD

**Issue by wzy98430** [TkzcM/pandownload-login#4]
#3 下载时日志显示403
![PD](https://user-images.githubusercontent.com/39153389/83423468-96f87300-a45d-11ea-97fa-435fa41860e2.png)
![日志](https://user-images.githubusercontent.com/39153389/83423477-99f36380-a45d-11ea-8337-c54252bff460.png)

**Comment by Vocare123** [comment]
下载目前一直都失败，等待有能力的大佬援助

**Comment by wzy98430** [comment]
> 下载目前一直都失败，等待有能力的大佬援助

那请问现在还有什么pandownload的替代方法吗？充了svip还是被限速，已经彻底绝望了
