### ISSUE TITLE
小文件下载没问题，大文件无法下载

### ISSUE THREAD

**Issue by aioscn** [TkzcM/pandownload-login#6]
小于30M的可以下载，但是大于30M的就没法下载了，提示获取下载连接失败（2）

**Comment by TkzcM** [comment]
不解决下载问题

**Comment by Vocare123** [comment]
> 不解决下载问题

抱住大佬的大腿！

**Comment by twu2** [comment]
可能程式裡面 proxy 沒處理好?
基本上只要能跳過登入的地方, 後面轉用其他的 proxy (如果有能夠用的 http proxy) 就能正常下載了.

例如, 有一台 squid proxy 在 192.168.0.1:8080
這時先執行 pdproxy, 在登入之後, ctrl-c 結束 pdproxy. 然後執行 
netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=8888 connectaddress=192.168.0.1 connectport=8080
就可以把 127.0.0.1:8888 轉到 192.168.0.1:8080 的 squid proxy.
這時後續的動作都可以正常執行了.

**Comment by TkzcM** [comment]
> 可能程式裡面 proxy 沒處理好?
> 基本上只要能跳過登入的地方, 後面轉用其他的 proxy (如果有能夠用的 http proxy) 就能正常下載了.

修复内存泄漏工具的作用就是关掉 aria2 的 proxy，主要问题还是原来的接口坏掉了
