### ISSUE TITLE
报告大佬，你的劳动成果被有心人盗取！

### ISSUE THREAD

**Issue by Vocare123** [TkzcM/pandownload-login#8]
https://www.52pojie.cn/thread-1191900-1-1.html

**Comment by aioscn** [comment]
哎，我还保留大神的连接，那家伙盗用我的不说，还把连接全删了

**Comment by Vocare123** [comment]
![photo_2020-06-03_10-24-16](https://user-images.githubusercontent.com/25167375/83588629-652dfc00-a584-11ea-98db-5c4eca08ff47.jpg)
没说是自己原创，连个出处都不加，就为了在论坛获取人气，我真的吐了

**Comment by aioscn** [comment]
带出处是对作者最基本的尊重




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vocare123"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 上午10:25
收件人: "TkzcM/pandownload-login"<pandownload-login@noreply.github.com&gt;; 
抄送: "箫篮剑"<313989877@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TkzcM/pandownload-login] 报告大佬，你的劳动成果被有心人盗取！ (#8)





 

 没说是自己原创，连个出处都不加，就为了在论坛获取人气，我真的吐了

**Comment by Vocare123** [comment]
> 带出处是对作者最基本的尊重
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Vocare123"<notifications@github.com&gt;; 发送时间: 2020年6月3日(星期三) 上午10:25 收件人: "TkzcM/pandownload-login"<pandownload-login@noreply.github.com&gt;; 抄送: "箫篮剑"<313989877@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [TkzcM/pandownload-login] 报告大佬，你的劳动成果被有心人盗取！ (#8) 没说是自己原创，连个出处都不加，就为了在论坛获取人气，我真的吐了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这人在刻意回避

**Comment by aioscn** [comment]
谁回避？我又不是论坛那人，论坛那人还复制我的话术呢

**Comment by aioscn** [comment]
https://www.aioscn.com/jiaochengjiqiao/bdstoken.html这是我的，保留作者出处
