### ISSUE TITLE
大佬 win10闪退是为啥呢

### ISSUE THREAD

**Issue by Fantasticccboy** [TkzcM/pandownload-login#9]
https://s1.ax1x.com/2020/06/03/tUHA9U.png
如图 报异常

**Comment by twu2** [comment]
通常是你的系統有別的程式 listen 8888 那個 port 了.
netstat -nab 看一下是那個程式佔住了.

**Comment by Fantasticccboy** [comment]
> 通常是你的系統有別的程式 listen 8888 那個 port 了.
> netstat -nab 看一下是那個程式佔住了.

thks 确实是这样 忘了正在搬砖。。
